### ISSUE TITLE
Raspberry Pi with wiringPi library

### ISSUE THREAD

**Issue by alexpagri** [Seeed-Studio/Grove_LED_Bar#10]
I recently downloaded the library and edited it to run with wiringPi library.

I can only power up all leds but not toggle them or use any of the examples from this repo because the led bar won't change at all...

I have some questions :  Is there any delay between those "digitalWrite(x,y)" or "digitalRead(x)" ?
                                        Why when I swap the Clock and the Data pin and run an example the led changes but in a different, incorrect way ?

I have the LED Bar v1.0 version.

I can upload some code if it is needed...

I tried different ways, such as totally randoming the time for outputs, and it was kind of chaotic.....

I only need some explanation on how to use the Clock & Data pins to simply toggle a led and I mean in which order should the combination be ....

And yes, I connected it directly to the GPIO board.

JUST found something ... http://learn.linksprite.com/raspberry-pi/linker-kit-for-raspberry-pi/how-to-use-linker-led-bar-on-the-raspberry/

I'll keep in touch if I solve it!

Still the same on linksprite's code ... 

PARTIALLY SOLVED : The main problem was that I also used a resistor. And in order for __state to be updated I have to plug VCC to an modifiable GPIO and reset the power with a delay of 1 microsec each time.

ALSO : if I set all leds to max brightness and the 5th (example) to half brightness it will start flashing like hell...

Thank you !

**Comment by awong1900** [comment]
Hi @alexpagri ，

Are you solved it ?

It is ok on Arduino?

Ten

**Comment by alexpagri** [comment]
@awong1900 

The problem is partially solved : 

I use a Raspberry pi 2 rev B and     in order to reset the leds ( change them ) , I have to cut the power. 

I cannot consider this a problem , I was just trying to set up the library successfully on my device.

Sorry for not updating the issue ....

I don't have an Arduino.




This issue can be closed .
