### ISSUE TITLE
Do not compile again

### ISSUE THREAD

**Issue by iGreybear** [Seeed-Studio/Grove_LED_Bar#11]
When compile appears these errors:

In file included from Level_bar.ino:12:
C:\Users\domenico\Documents\Arduino\libraries\Grove_LED_Bar-master/Grove_LED_Bar.h: In member function 'void Grove_LED_Bar::begin()':
C:\Users\domenico\Documents\Arduino\libraries\Grove_LED_Bar-master/Grove_LED_Bar.h:53: error: 'OUTPUT' was not declared in this scope
C:\Users\domenico\Documents\Arduino\libraries\Grove_LED_Bar-master/Grove_LED_Bar.h:53: error: 'pinMode' was not declared in this scope

MY SOLUTION:

Add:
#include <Arduino.h>

at beginning of the sketch.

**Comment by awong1900** [comment]
Thanks for your help. We add #include Arduino.h to Grove_LED_Bar.h file. 
Please to test it.
