### ISSUE TITLE
Inconsistent license information

### ISSUE THREAD

**Issue by aidan-fitz** [Seeed-Studio/Grove_LED_Bar#13]
The `README.md` and `LICENSE` files both say that this program is under the MIT License; however, the comment at the top of `Grove_LED_Bar.cpp/.h` says "All right [sic] reserved" and the LGPL. ("All rights reserved" is incorrect because an open source license is ["Some rights reserved"](https://en.wikipedia.org/wiki/File:CC_some_rights_reserved.svg).)

**Comment by loovee** [comment]
Sorry made a mistake. 
Fixed.
