### ISSUE TITLE
Can this module be used directly with the Raspberry Pi?

### ISSUE THREAD

**Issue by RyuuzakiJulio** [Seeed-Studio/Grove_LED_Bar#16]
I only need this single module and I don't want to buy a whole GrovePi_Plus to connect it to. Is there an easier way to connect this module and use python to control it directly from a Raspberry Pi?

**Comment by Pillar1989** [comment]
It's just a wire connection. It's not a software problem.

**Comment by awong1900** [comment]
You need native driver.
