### ISSUE TITLE
library.properties version is not correct

### ISSUE THREAD

**Issue by fpistm** [Seeed-Studio/Grove_LED_Bar#26]
https://github.com/Seeed-Studio/Grove_LED_Bar/blob/595b152bbd23123dc193f337fbbfdea932f20f73/library.properties#L2

It should be 1.0.1 to be aligned with the tag release.
As a consequence, the Arduino Board manager only see 1.0.0.

I would advice to update to 1.0.2 and do a new release to fix this.

**Comment by ackPeng** [comment]
Thank you very much, very useful suggestions

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
