### ISSUE TITLE
Python version for people who don't own a GrovePi+

### ISSUE THREAD

**Issue by designdevy** [Seeed-Studio/Grove_LED_Bar#27]
Hi, I use a lot of Grove modules with Raspberry Pi but I don't prefer using GrovePi+. Can someone from Seeed help port it out to normal Python3 usage instead of using through GrovePi. Thanks in advance.

**Comment by gughpatrik619** [comment]
I would also be thankfull, I'm using the Grove Base HAT for Raspberry Pi 3 B.

**Comment by ackPeng** [comment]
@designdevy Is this problem solved?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
