### ISSUE TITLE
Solution for using with ESP

### ISSUE THREAD

**Issue by GuyIUT** [Seeed-Studio/Grove_LED_Bar#33]
Currently, the library available on the Seedstudio website cannot be used for the ESP32 board with the Arduino IDE. When we try to compile all the examples, many errors appear on the min and max functions in Grove_LED_bar.cpp.
I have solve all the problems by implementing parameter casting **(in bold)** in the function call. This file must be modified as follows:
line 97 level = max(0, min(10, **(int)** level));
line 117 led = max(1, min(10, **(int)** led));
line118 brightness = max(0, min(**(int)** brightness, 1));
line 138 led = max(1, min(10, **(int)** led));

**Comment by ackPeng** [comment]
Thanks a lot, could you please submit a PR for us?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
